# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('locations', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('landmark', models.CharField(max_length=100)),
                ('restaurantphn', models.CharField(max_length=100)),
                ('restaurantemail', models.EmailField(max_length=254)),
                ('openingstatus', models.CharField(choices=[('Open', 'Open'), ('Opening Soon', 'Opening Soon')], max_length=60)),
                ('restaurantweb', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='restaurant',
        ),
    ]
