# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20170608_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='first_aid',
            field=models.BooleanField(default=True),
        ),
    ]
