# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_blog_first_aid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='first_aid',
        ),
    ]
