# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_remove_blog_openingstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='my_field',
            new_name='features',
        ),
    ]
