# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 06:56
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_remove_blog_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='openingstatus',
            field=models.CharField(choices=[('Open', 'Open'), ('Opening Soon', 'Opening Soon')], default=0, max_length=60),
        ),
        migrations.AddField(
            model_name='blog',
            name='zipcode',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Delivery', 'Delivery'), ('Take-Away', 'Take-Away')], default=0, max_length=18),
        ),
    ]
