# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 07:18
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_auto_20170609_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='timing',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], default=0, max_length=27),
        ),
    ]
