# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_blog_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='From',
            field=models.CharField(choices=[('00:00', '00:00'), ('00:15', '00:15'), ('00:30', '00:30'), ('00:45', '00:45'), ('00:60', '00:60'), ('01:00', '01:00'), ('01:15', '01:15')], default=0, max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='To',
            field=models.CharField(choices=[('00:00', '00:00'), ('00:15', '00:15'), ('00:30', '00:30'), ('00:45', '00:45'), ('00:60', '00:60'), ('01:00', '01:00'), ('01:15', '01:15')], default=0, max_length=60, unique=True),
        ),
    ]
